import "./globals.css"
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

import Header from "@/components/Header"
import Footer from "@/components/Footer"
import { ReactQueryProvider } from "./ReactQueryProvider"

export const metadata = {
  title: "Kazhmuratov Bureau",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ReactQueryProvider>
        <body>
          <Header />
          <main>{children}</main>
          <Footer />
        </body>
      </ReactQueryProvider>
    </html>
  )
}
